Feature/id 23/api gateway
sofdev6-02-2024/Solidarios pull request #20
Opened 2024-10-29 21:30 UTC by Elvis-Castro-H

## Pull Request
**Clickup:** https://app.clickup.com/t/868ac266e

## Reviewers
@victor-fundacion 
@JP-Arequipa

2024-10-29 22:51 UTC, victor-fundacion requested changes
Resolve merge conflicts

2024-10-29 22:58 UTC, victor-fundacion requested changes
Create Readme on how to start the api and test it with other services

2024-10-30 15:10 UTC, victor-fundacion requested changes
I followed the steps on each Readme and could not register a service in service discovery.
1.  I run docker compose (to init sql and consul)
![image](https://github.com/user-attachments/assets/a2194e4c-edc2-42b4-a987-0253f5bd939b)
2. Started the service discovery service manually
![image](https://github.com/user-attachments/assets/1886580a-4736-4724-aebc-a1ad872739d6)
3. Started the CEventservice.api service and gateway
4. Made a POST request to `POST` request to `/api/service-registry/register`
with:
{
  "serviceName": "cevent-service",
  "address": "localhost",
  "port": 5000,
  "healthCheckEndpoint": "/health"
}

Got this error:
![image](https://github.com/user-attachments/assets/a99a8d5a-5025-45cb-af17-b9030b5868ff)

Consul up:
![image](https://github.com/user-attachments/assets/010cce52-57f4-4e42-a1ed-2a0513f895e2)

2024-10-30 15:10 UTC, victor-fundacion commented on apps/docker-compose.yml
> +      dockerfile: Dockerfile
Service Discovery can not be started.
![Screenshot from 2024-10-30 10-46-44](https://github.com/user-attachments/assets/65e066c4-8150-4f3f-ad71-3160e2cb0bb2)

2024-10-30 18:46 UTC, victor-fundacion commented
@Elvis-Castro-H Add git ignore to your apigateway and servicediscovery

2024-10-30 19:39 UTC, Elvis-Castro-H commented
@victor-fundacion I already added a .gitignore file in each service implemented, I also added a general .gitignore in the root of apps

2024-11-01 18:49 UTC, victor-fundacion approved these changes
Observations solved and apigatway working correctly.
![image](https://github.com/user-attachments/assets/ea993665-93c0-4d1b-8625-a3747803989a)

2024-11-01 18:58 UTC, JP-Arequipa approved these changes

2024-11-01 18:59 UTC, merged