Feature/id 31/jwt authorization
sofdev6-02-2024/Solidarios pull request #24
Opened 2024-10-31 02:09 UTC by victor-fundacion

2024-10-31 02:16 UTC, CatCoder36 commented
Please add a description toRename the folder name of this service to EventService and add a description to your user story

2024-10-31 14:26 UTC, victor-fundacion commented
> Please add a description toRename the folder name of this service to EventService and add a description to your user story @victor-fundacion

@CatCoder36, First, the rename of foder was not consulted to the team, and overall, it is out of this User Story scope. Rember it is about Authorization, and the service you want me to rename has been worked on for almost 2 weeks. And Secondly, The user story had previous description and acceptance criteria (you can check the timeline). But, you are right, I forgot to add it to my PR's description. Thxs.

2024-10-31 19:37 UTC, Elvis-Castro-H requested changes
For testing reasons I protected the endpoint to get all the events
![image](https://github.com/user-attachments/assets/6f8d59b2-814a-43f5-b9a7-e33b6c3dc84b)

When I tried to do a get without being logged in this was allowed
![image](https://github.com/user-attachments/assets/81d902a0-7df6-4c05-841b-4619d8878a41)
![image](https://github.com/user-attachments/assets/89a7e3f1-2dfb-49a5-b283-a57249e3e17a)

2024-11-06 22:27 UTC, CatCoder36 commented on apps/cevent_frontend/src/app/my_tickets/page.tsx
>  export default function MyTicketsPage() {
Why does my ticket page currently require me to check the authentication status?

2024-11-06 22:27 UTC, CatCoder36 commented on apps/cevent_frontend/src/utils/interfaces/EventInterfaces.ts
> +interface Event {
Please consider not replacing the above existing event interfaces with a more general one.

2024-11-06 22:27 UTC, CatCoder36 commented on apps/docker-compose.yml
> +    image: mcr.microsoft.com/mssql/server:2019-latest
Why replace sql server 2022 with 2019?

2024-11-11 18:40 UTC, CatCoder36 approved these changes

2024-11-11 23:09 UTC, Elvis-Castro-H approved these changes

2024-11-11 23:09 UTC, merged