Feature/id 41/Add Checkout Modal
sofdev6-02-2024/Solidarios pull request #38
Opened 2024-11-21 18:16 UTC by gabitrujillo

2024-11-21 18:45 UTC, victor-fundacion approved these changes

2024-11-21 18:45 UTC, victor-fundacion requested changes
Fix, CI errors

2024-11-21 18:58 UTC, victor-fundacion approved these changes

2024-11-21 23:39 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +  // Calculate platform fee (3% of total price)
Delete comment.

2024-11-21 23:39 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +  // Calculate final total price after adding the platform fee
Delete comment.

2024-11-21 23:39 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +  const coverPhotoUrl = searchParams.get('coverPhotoUrl'); // Imagen del evento
Delete comment.

2024-11-21 23:39 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +        {/* Left Section: Payment Form */}
Delete comment.

2024-11-21 23:39 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +                src={coverPhotoUrl} // Imagen dinámica
Delete comment.

2024-11-21 23:39 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +        {/* Right Section: Order Summary */}
Delete comment.

2024-11-21 23:39 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +            {/* Imagen del evento */}
Delete comment.

2024-11-21 23:40 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +                  width: '100%', // Ancho completo
Delete comment.

2024-11-21 23:40 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +                  height: 'auto', // Mantiene la proporción
Delete comment.

2024-11-21 23:40 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +                  borderRadius: '8px', // Bordes redondeados
Delete comment.

2024-11-21 23:40 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +                  marginBottom: '16px', // Espacio debajo de la imagen
Delete comment.

2024-11-21 23:40 UTC, Karvlox commented on apps/cevent_frontend/src/app/checkout/page.tsx
> +            {/* Resumen de la orden */}
Delete comment.

2024-11-22 03:10 UTC, Karvlox approved these changes

2024-11-22 03:10 UTC, merged